config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get '/dashboard', to: 'dashboard#show'
  
  resources :users, except: [:new, :update, :index]
  resources :activities
  resources :roles do 
    resources :volunteers, only: [:index]
  end
  resources :volunteers do
    resources :activities, only: [:new, :create, :index] 
  end
end

app/models/volunteer.rb
class Volunteer < ApplicationRecord
  belongs_to :user
  has_many :activities, dependent: :destroy
  has_many :roles, through: :activities

  enum age_group: {over_eighteen: 0, over_twenty_one: 1, under_eighteen: 2}
  enum background_check_status: {incomplete: 0, approved: 1, flagged: 2}
  
  validates :first_name, :last_name, :background_check_status, :age_group, presence: true
  validate :one_contact_method_must_be_present
  validate :birthdate_must_be_in_reasonable_past

  scope :alpha, -> {order(:last_name, :first_name).distinct}


  def full_name
    "#{first_name} #{last_name}"
  end

  def total_hours
    activities.sum(:duration)
  end

  def start_year
    created_at.year
  end

  def last_activity_date
    activities.maximum(:date)
  end

  def self.apply_query(query)
    if query.present?
      case query
      when "last_name"
        alpha
      when "first_name"
        order(:first_name)
      when "date"
        left_joins(:activities).group('volunteers.id').order('max(date) desc')
      when "hours"
        left_joins(:activities).group('volunteers.id').order('sum(duration) desc')
      else
        search_by_full_name(query)
      end
    else
      alpha
    end
  end

  def self.search_by_full_name(query)
    q = "%#{query}"
    where("first_name || ' ' || last_name LIKE ? OR first_name LIKE ? OR last_name LIKE ?", q, q, q)
  end

  private
  def one_contact_method_must_be_present
    if !email.present? && !phone.present?
      errors.add(:phone, "or email must be present")
    end
  end

  def birthdate_must_be_in_reasonable_past
    if birthday 
      if birthday > Date.today || birthday.year < 1910
        errors.add(:birthday, "must be in the past (but not ancient history)")
      end
    end
  end
end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController
  before_action :find_volunteer, :redirect_if_not_authorized, only: [:show, :edit, :update, :destroy]
  #find_volunteer must come before redirect so that @volunteer has a value

  def index
    flash.now[:search_guide] = "Please enter a name" if params[:query] == ""

    #handle nested route /volunteers/:volunteer_id/activities
    if params[:role_id] && @role = current_user.roles.find_by(id: params[:role_id])
      @volunteers = @role.volunteers.alpha 
    else
      flash.now[:alert] = "Role not found" if params[:role_id]
      @volunteers = current_user.volunteers.apply_query(params[:query])
    end
  end

  def show
  end
  
  def new
    @volunteer = Volunteer.new
  end

  def create
    @volunteer = current_user.volunteers.build(volunteer_params)
    if @volunteer.save
      redirect_to volunteer_path(@volunteer)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @volunteer.update(volunteer_params)
      redirect_to volunteer_path(@volunteer)
    else
      render :edit
    end
  end

  def destroy
    @volunteer.destroy
    redirect_to dashboard_path
  end

  private
  def volunteer_params
    params.require(:volunteer).permit(:first_name, :last_name, :email, :phone, :occupation, :employer, :birthday, :age_group, :background_check_status, :photo, :interests)
  end

  def redirect_if_not_authorized
    if @volunteer.user != current_user
      flash[:alert] = "Invalid record"
      redirect_to dashboard_path
    end
  end

  def find_volunteer
    @volunteer = Volunteer.find(params[:id])
  end
end

app/helpers/volunteers_helper.rb
module VolunteersHelper

  def display_age_group(volunteer)  
    volunteer.age_group.gsub('_', " ").gsub("twenty one", "21").gsub("eighteen", "18").capitalize
  end

  def display_phone(phone)
    phone.gsub(".", "-")
  end

  def display_profile_image(volunteer)
    if volunteer.photo.present?
      image_tag("#{volunteer.photo}", alt: "#{volunteer.full_name}")
    else
      image_tag("undraw_polaroid_gg6n.svg", alt: "Volunteer profile image placeholder")
    end
  end
end

app/views/volunteers/_form.html.erb
<%= render partial: '/shared/validation_errors', locals: {object: volunteer}%>

<%= form_for volunteer do |f| %>
  <%= f.label :first_name, class: "required" %><br>
  <%= f.text_field :first_name, required: true %><br>
  <%= f.label :last_name, class: "required" %><br>
  <%= f.text_field :last_name, required: true %><br>
  <%= f.label :phone %><br>
  <%= f.telephone_field :phone, placeholder: '(xxx) xxx-xxxx' %><br>
  <%= f.label :email %><br>
  <%= f.email_field :email %><br>
  <%= f.label :occupation %><br>
  <%= f.text_field :occupation %><br>
  <%= f.label :employer %><br>
  <%= f.text_field :employer %><br>
  <%= f.label :birthday %><br>
  <%= f.date_field :birthday %><br>
  <%= f.label :age_group, class: "required" %><br>
  <%= f.select :age_group, [["Under 18", "under_eighteen"], ["18-21", "over_eighteen"], ["Over 21", "over_twenty_one"]], required: true %><br>
  <%= f.label :background_check_status, class: "required" %><br>
  <%= f.select :background_check_status, [["Incomplete", "incomplete"], ["Approved", "approved"], ["Flagged", "flagged"]], required: true %><br>
  <%= f.label :photo, "Photo link" %><br>
  <%= f.url_field :photo %><br>
  <%= f.label :interests %><br>
  <%= f.text_area :interests %><br>
  <%= f.submit "Save" %>
<% end %>

app/views/volunteers/_role_links.html.erb
<%= link_to role.title, role_path(role) %>

app/views/volunteers/_volunteer.html.erb
<tr class="table-content">
  <td><%= link_to volunteer.first_name, volunteer_path(volunteer) %></td>
  <td><%= volunteer.last_name %></td>
  <% if role %>
    <td><%= display_phone(volunteer.phone) %></td>
    <td><%= mail_to volunteer.email %></td>
  <% else %>
    <td><%= display_date(volunteer.last_activity_date) %></td>
    <td><%= display_hours(volunteer.total_hours) %></td>
  <% end %>
</tr>

app/views/volunteers/edit.html.erb
<h1>Edit a volunteer</h1>
<%= render partial: 'form', locals: {volunteer: @volunteer } %>

app/views/volunteers/index.html.erb
<%= render partial: '/shared/flash_alerts' %>

<div class="flex-row">
  <div>
    <% if @role %>
      <h1>Volunteers - <%= @role.title.titlecase %></h1>
    <% else %>
      <h1>Volunteers</h1>
    <% end %>
  </div>
  <div>
    <%= link_to "Add new volunteer", new_volunteer_path, class: "button" if !@role %>
  </div>
</div>

<% if !@role %>
  <div class="search-bar">
    <%= form_tag volunteers_path, method: :get do %>
      <%= text_field_tag :query, nil, placeholder: "Search by name" %>
      <%= submit_tag "Search", name: nil, class: "button-search"%> 
    <% end %>
    <%= render partial: '/shared/flash_search_guide' %>
  </div>
<% end %>

<div class="scroll">
  <table class="full-width">
    <thead>
      <tr>
        <% if @role %>
          <th>First name</th>
          <th>Last name</th>
          <th>Phone</th>
          <th>Email</th>
        <% else %>
          <th><%= link_to "First name", :query => "first_name" %></th>
          <th><%= link_to "Last name", :query => "last_name" %></th>
          <th><%= link_to "Last volunteer date", :query => "date" %></th>
          <th><%= link_to "Total hours", :query => "hours" %></th>
        <% end %>
      <tr>
    </thead>
    <tbody>
      <%= render partial: 'volunteer', collection: @volunteers, locals: {role: @role} %> 
      <%= message_if_no_records(@volunteers) %>
    </tbody>
  </table>
</div>

app/views/volunteers/new.html.erb
<h1>Add a new volunteer</h1>
<p>Include at least one contact method</p>
<%= render partial: 'form', locals: {volunteer: @volunteer} %>

app/views/volunteers/show.html.erb
<div class="grid-container profile">
  <div class="grid-sidebar">
    <%= display_profile_image(@volunteer) %>
    <div>
      <p>Volunteer since <%= @volunteer.start_year %></p>
      <p>Total hours: <%= display_hours(@volunteer.total_hours) %></p>
      <p><%= link_to 'See all activity records', volunteer_activities_path(@volunteer), class: "emphasis" %></p>
      <p><%= link_to 'Edit volunteer', edit_volunteer_path(@volunteer), class: "emphasis" %></p>
    </div>
    <div>
      <%= button_to 'X Delete volunteer', volunteer_path(@volunteer), method: :delete, 
        data: {confirm: "ALERT: Deleting this volunteer will also delete all of their activity records. Do you want to continue?" },
        class: "button delete" %>
    </div>
  </div>
  
  <div class="grid-main">
    <div class="flex-row">
      <h1><%= @volunteer.full_name %></h1>
      <%= link_to "Add new activity", new_volunteer_activity_path(@volunteer), class: "button" %>
    </div>

    <div>
      <p><span class="emphasis">Phone: </span><%= @volunteer.phone %></p>
      <p><span class="emphasis">Email: </span><%= mail_to @volunteer.email %></p>
    </div>
    
    <hr>  
  
    <div>
      <p><span class="emphasis">Background check status: </span><%= @volunteer.background_check_status.capitalize %><p>
      <p><span class="emphasis">Occupation: </span><%= @volunteer.occupation %></p>
      <p><span class="emphasis">Employer: </span><%= @volunteer.employer %></p>
      <p><span class="emphasis">Birthday: </span><%= display_date(@volunteer.birthday) %></p>
      <p><span class="emphasis">Age range: </span><%= display_age_group(@volunteer) %></p>
      <p><span class="emphasis">Interests: </span><%= @volunteer.interests %></p>
      <p><span class="emphasis">Roles: </span><span class="primary-color"><%= render partial: 'role_links', collection: @volunteer.roles.distinct, as: :role, spacer_template: 'shared/comma' || "No roles" %></span></p>
    </div>
  </div>
</div>