config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get '/dashboard', to: 'dashboard#show'
  
  resources :users, except: [:new, :update, :index]
  resources :activities
  resources :roles do 
    resources :volunteers, only: [:index]
  end
  resources :volunteers do
    resources :activities, only: [:new, :create, :index] 
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    @user = current_user
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  
  def new_user_welcome
    if current_user.volunteers.size == 0 && current_user.roles.size == 0
    content_tag(:div, content_tag(:p, "This dashboard will display stats as you add volunteers
     roles and activity records.") + content_tag(:p, "To get started, add a volunteer and a role.
     Then start tracking each volunteer engagement as an activity record."), class: "welcome")
    end
  end

  def message_if_no_birthdays
    "No birthdays to display" if current_user.birthday_list.size == 0
  end
end

app/views/dashboard/_birthday_list.html.erb
<p><%= link_to volunteer.full_name, volunteer_path(volunteer) %> - <%= Date.today.strftime("%B") %> <%= volunteer.birthday.day %></p>

app/views/dashboard/show.html.erb
<%= render partial: '/shared/flash_alerts' %>

<div class="dashboard">
  <h1>Welcome, <%= @user.username %></h1>
  
  <div class="link-block">
    <%= link_to "Add volunteer", new_volunteer_path %> | <%= link_to "Add role", new_role_path %> | <%= link_to "Add activity record", new_activity_path %> | <%= link_to "Account", user_path(@user) %>
    <hr>
  </div>

  <h2>Volunteer Engagement Highlights</h2>
  <%= new_user_welcome %>
  <div class="tri-flex-container">
    <div>
      <h3>This month</h3>
      <p><span class="emphasis">Total hours: </span><%= display_hours(@user.hours_this_month) %></p>
      <p><span class="emphasis">Total engagements: </span><%= @user.activities_this_month %> </p>
      <p><span class="emphasis">Unique volunteers: </span><%= @user.unique_volunteers_this_month %></p>
    </div>
    <div>
      <h3>This year</h3>
      <p><span class="emphasis">Total hours: </span><%= display_hours(@user.hours_this_year) %></p>
      <p><span class="emphasis">Total engagements: </span><%= @user.activities_this_year %></p>
      <p><span class="emphasis">Unique volunteers: </span><%= @user.unique_volunteers_this_year %></p>
    </div>
    <div>
      <h3>Cummulative</h3>
      <p><span class="emphasis">Total hours: </span><%= display_hours(@user.total_hours) %></p>
      <p><span class="emphasis">Total engagements: </span><%= @user.total_activities %></p>
      <p><span class="emphasis">Unique volunteers: </span><%= @user.unique_volunteers %></p>
    </div>
  </div>
  <div>
    <h3 id="birthday-heading">Birthdays this month</h3>
    <%= render partial: 'birthday_list', collection: @user.birthday_list, as: :volunteer %>
    <%= message_if_no_birthdays %>
  </div>
</div>