config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get '/dashboard', to: 'dashboard#show'
  
  resources :users, except: [:new, :update, :index]
  resources :activities
  resources :roles do 
    resources :volunteers, only: [:index]
  end
  resources :volunteers do
    resources :activities, only: [:new, :create, :index] 
  end
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :volunteer
  belongs_to :role

  validates :date, :duration, :volunteer_id, :role_id, presence: true
  validates :duration, numericality: {greater_than: 0, less_than_or_equal_to: 24} #make it a float?
  validate :date_cannot_be_in_future

  scope :newest, -> {order(date: :desc)}
  scope :oldest, -> {order(:date)}

  def self.apply_query(query)
    if query.present?
      case query
      when "oldest"
        oldest.includes(:volunteer, :role)
      when "newest"
        newest.includes(:volunteer, :role)
      when "name"
        includes(:volunteer, :role).order('volunteers.last_name')
      when "role"
        includes(:volunteer, :role).order('roles.title')
      when "duration"
        includes(:volunteer, :role).order(duration: :desc)
      else
        q = "%#{query}"
        includes(:volunteer, :role).where("first_name || ' ' || last_name LIKE ? OR first_name LIKE ? OR last_name LIKE ?", q, q, q)
      end
    else
      newest.includes(:volunteer, :role) #includes greatly speeds up querying
    end
  end

  private
  def date_cannot_be_in_future
    if date && date > Date.today
      errors.add(:date, "can't be in the future")
    end
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :find_activity, :redirect_if_not_authorized, only: [:show, :edit, :update, :destroy]
  before_action :validate_role_and_volunteer_belong_to_user, only: [:create, :update]
  
  def index
    flash.now[:search_guide] = "Please enter a name" if params[:query] == ""

    if params[:volunteer_id] && @volunteer = current_user.volunteers.find_by(id: params[:volunteer_id]) #handle nested route /volunteers/:volunteer_id/activities
      @activities = @volunteer.activities.apply_query(params[:query])
    else
      flash.now[:alert] = "Volunteer not found" if params[:volunteer_id]
      @activities = current_user.activities.apply_query(params[:query])
    end
  end

  def show
  end

  def new
    if params[:volunteer_id] && @volunteer = current_user.volunteers.find_by(id: params[:volunteer_id])
      @activity = @volunteer.activities.build
    else
      flash[:alert] = "Volunteer not found" if params[:volunteer_id]
      @activity = Activity.new
      set_user_volunteers
    end
    set_user_roles
  end

  def create
    @activity = current_user.activities.build(activity_params)
    if @activity.save
      redirect_to activity_path(@activity)
    else 
      if params[:volunteer_id] #if nested form has errors, need to render with @volunteer value still set
        @volunteer = current_user.volunteers.find_by(id: params[:volunteer_id]) 
      else
        set_user_volunteers
      end
      set_user_roles
      render :new
    end
  end

  def edit
    set_user_volunteers
    set_user_roles
  end

  def update
    if @activity.update(activity_params)
      redirect_to activity_path(@activity)
    else
      set_user_volunteers
      set_user_roles
      render :edit
    end
  end

  def destroy
    @activity.destroy
    redirect_to dashboard_path
  end

  private
  def activity_params
    params.require(:activity).permit(:date, :duration, :volunteer_id, :role_id)
  end

  def find_activity
    @activity = Activity.find(params[:id])
  end

  def redirect_if_not_authorized
    if @activity.volunteer.user != current_user
      flash[:alert] = "Invalid record"
      redirect_to dashboard_path
    end
  end

  def validate_role_and_volunteer_belong_to_user
    role_id = params[:activity][:role_id]
    volunteer_id = params[:volunteer_id] || params[:activity][:volunteer_id]
    if (role_id != "" && current_user.roles.find_by(id: role_id).nil?) || (volunteer_id != "" && current_user.volunteers.find_by(id: volunteer_id).nil?)
      flash[:alert] = "You can only save/alter activity records for volunteers and roles you've created"
      redirect_to new_activity_path
    end
  end

  def set_user_volunteers
    @volunteers = current_user.volunteers.alpha
  end

  def set_user_roles
    @roles = current_user.roles.alpha
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_activity.html.erb
<tr class="table-content">
  <td><%= link_to display_date(activity.date), activity_path(activity) %></td>
  <td><%= activity.volunteer.full_name if !volunteer %></td>
  <td><%= activity.role.title %></td>
  <td><%= display_hours(activity.duration) %></td>
</tr>

app/views/activities/_form.html.erb
<%= render partial: '/shared/validation_errors', locals: {object: activity} %>
<%= render partial: '/shared/validation_errors', locals: {object: volunteer} if volunteer %>

<%= form_for [volunteer, activity] do |f| %>
  <%= f.label :date, class: "required" %><br>
  <%= f.date_field :date, required: true %><br>
  <%= f.label :duration, "Duration (hrs)", class: "required" %><br>
  <%= f.number_field :duration, min: 0.25, step: 0.25, required: true %><br>
  <% if volunteer %>
    <%= f.hidden_field :volunteer_id, value: volunteer.id %>
  <% else %>
    <%= f.label :volunteer_id, "Volunteer", class: "required" %><br>
    <%= f.collection_select :volunteer_id, volunteers, :id, :full_name, prompt: true, required: true %><br>
  <% end %>
  <%= f.label :role_id, "Role", class: "required" %><br>
  <%= f.collection_select :role_id, roles, :id, :title, prompt: true, required: true %><br>
  <%= f.submit "Save" %>
<% end %>

app/views/activities/edit.html.erb
<h1>Edit an activity</h1>
<%= render partial: 'form', locals: {activity: @activity, volunteers: @volunteers, roles: @roles, volunteer: nil} %>

app/views/activities/index.html.erb
<%= render partial: '/shared/flash_alerts' %>

<div class="flex-row">
  <div>
    <h1>Activity Records<%= " for #{@volunteer.full_name}" if @volunteer %></h1>
  </div>
  <div>
    <% if @volunteer %>
      <%= link_to "Add new record for #{@volunteer.first_name}", new_volunteer_activity_path(@volunteer), class: "button" %>
    <% else %>
      <%= link_to "Add new record", new_activity_path, class: "button" %>
    <% end %>
  </div>
</div>

<% if !@volunteer %>
  <div>
    <div class="filter-options">
      <span>Sort by <%= link_to "Newest", activities_path(query: "newest") %> | 
      <%= link_to "Oldest", activities_path(query: "oldest") %></span>
    </div>
    <div class="search-bar">
      <%= form_tag activities_path, method: :get do %>
        <%= text_field_tag :query, nil, placeholder: "Search by volunteer name" %>
        <%= submit_tag "Search", name: nil %>
      <% end %>
      <%= render partial: '/shared/flash_search_guide' %>
    </div>
  </div>
<% end %>

<div class="scroll">
  <table class="full-width">
    <thead>
      <tr>
        <th><%= link_to "Date", :query => "newest" %></th>
        <th><%= link_to "Volunteer", :query => "name" if !@volunteer %></th>
        <th><%= link_to "Role", :query => "role" %></th>
        <th><%= link_to "Duration (hrs)", :query => "duration" %></th>
      <tr>
    </thead>
    <tbody>
      <%= render partial: 'activity', collection: @activities, locals: {volunteer: @volunteer} %> 
      <%= message_if_no_records(@activities) %>
    </tbody>
  </table>
</div>

app/views/activities/new.html.erb
<%= render partial: 'shared/flash_alerts' %>
<h1>Add a new activity record<%= " for #{@volunteer.full_name}" if @volunteer %></h1>
<%= render partial: 'form', locals: {activity: @activity, volunteers: @volunteers, roles: @roles, volunteer: @volunteer} %>

app/views/activities/show.html.erb
<div class="flex-row">
  <div>
    <h1>Activity record</h1>
  </div>
  <div>
    <%= button_to "X Delete record", activity_path(@activity), method: :delete, class: "button delete" %>
  </div>
</div>

<div>
  <p>Date: <%= display_date(@activity.date) %></p>
  <p>Volunteer: <%= link_to @activity.volunteer.full_name, volunteer_path(@activity.volunteer) %></p>
  <p>Role: <%= link_to @activity.role.title, role_path(@activity.role) %></p>
  <p>Duration: <%= display_hours(@activity.duration) %> hours</p>
</div>

<div class="button-block">
  <%= link_to "Edit activity", edit_activity_path(@activity), class: "button" %>
</div>