config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get '/dashboard', to: 'dashboard#show'
  
  resources :users, except: [:new, :update, :index]
  resources :activities
  resources :roles do 
    resources :volunteers, only: [:index]
  end
  resources :volunteers do
    resources :activities, only: [:new, :create, :index] 
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VolunteerLog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;500;700&display=swap" rel="stylesheet">
  </head>

  <body>
    <div class="page-container">
    <% if current_user %>
    <nav>
      <div class="navbar">
        <div id="site-title">
          <%= link_to 'VolunteerLog', dashboard_path %> 
        </div>
        <div class= "nav-options">
          <%= link_to 'Volunteers', volunteers_path %>
          <span>|</span>
          <%= link_to 'Roles', roles_path %>
          <span>|</span>
          <%= link_to 'Activity Records', activities_path %>
          <span>|</span>
          <div class="dropdown">
              <span>Add New</span><span>|</span>
              <div class="dropdown-options">
                <%= link_to 'Add role', new_role_path %>
                <%= link_to 'Add volunteer', new_volunteer_path %>
                <%= link_to 'Add activity', new_activity_path %>
              </div>
            </div>
          <%= link_to 'Logout', logout_path, method: 'delete' %> 
        </div>
      </div>
      <hr>
    </nav>
    <% end %>
    
    <%= yield %>

    <div class="push"></div>
    </div>
    <footer>
      <div class="link-block">
        <%= link_to 'Home', dashboard_path %> | <%= link_to 'GitHub Repo', 'https://github.com/staceymck/volunteer-log' %>
      </div>
    </footer>
  </body>
</html>